### ISSUE TITLE
[Dev] Redesign pen tool of memo canvas view

### ISSUE THREAD

**Issue by dscyrescotti** [dscyrescotti/Memola#24]
### Description
So far, there are two pen tool developed and docked on the right bottom of memo canvas view. So, this is a call to redesign the pen tool of the canvas and to add the functionality for customizing pens based on the user's needs. It is also required to add color picker as well as thickness and opacity sliders.

### Todos
- [x] To implement customizable pen tool dock
- [x] To implement persistent for pen tools
- [x] To implement new pen button
- [x] To implement color picker
- [x] To implement opacity slider
- [x] To implement thickness slider
