### ISSUE TITLE
[Dev] Redesign memo canvas view

### ISSUE THREAD

**Issue by dscyrescotti** [dscyrescotti/Memola#28]
### Description
Since pen tool is redesigned properly, it is a good time to reskin the appearance of memo canvas view along with adding the missing components like memo title label, lock button and zoom option button.

### Todos
- [x] To implement memo title label
- [x] To add memo title editing option
- [x] To add zoom in-out option
- [x] To implement lock button
