### ISSUE TITLE
[Dev] Set up canvas renderer for memo

### ISSUE THREAD

**Issue by dscyrescotti** [dscyrescotti/Memola#3]
### Description
The renderer is built on the top of Metal to efficiently render graphics context using off-screen rendering technique.

### Todos
- [x] To set up Metal pipelines
- [x] To implement renderer
- [x] To implement off-screen rendering
