### ISSUE TITLE
[Dev] Add haptic effects on canvas view

### ISSUE THREAD

**Issue by dscyrescotti** [dscyrescotti/Memola#30]
### Description
This is a call to enhance user interaction and experience by adding haptic effects on button clicking and canvas zooming.

### Todos
- [ ] To add haptic effects on buttons
- [ ] To add haptic effects on pen dock
- [ ] To add haptic effects on canvas zooming
