### ISSUE TITLE
[Dev] Fine-tune memos grid view

### ISSUE THREAD

**Issue by dscyrescotti** [dscyrescotti/Memola#32]
### Description
This is a call to refine the appearance of memos grid view along with the addition of search bar and sorting options.

### Todos
- [x] To refine the grid view appearance
- [x] To add search bar
- [x] To add sort options
- [x] To add like action
- [x] To add delete action to memo (soft delete actually)
- [x] To show soft deleted memo
