### ISSUE TITLE
[Dev] Implement photo insertion

### ISSUE THREAD

**Issue by dscyrescotti** [dscyrescotti/Memola#44]
### Description
This is a call to implement photo insertion along with the selection of photo from photo library and capture of new photo. With that said, it will include the setup for photo render pipeline to render photo inserted along with persistence database setup.

### Todos
- [x] To add photo entity in persistence database
- [x] To create photo as graphic context's element
- [x] To implement photo picker buttons on canvas along with preview
- [x] To update render pipeline for photo
- [x] To make photo dimension fit its aspect ratio
- [x] To update history undo and redo logic
- [x] To optimize texture loading
