### ISSUE TITLE
[Dev] Fine tune memo canvas tool

### ISSUE THREAD

**Issue by dscyrescotti** [dscyrescotti/Memola#49]
### Description
So far since the render pipeline is optimized, it is a call to improve the memo tool to be more visual and interactive in terms of user experience. It includes the fine-tuning of animations and transitions of tool button items, photo preview and pen dock.

### Todos
- [x] To add hand grab icon button in tool bar indicating the canvas can be interacted freely
- [x] To enhance transition of photo element options
- [x] To double check lock feature
- [x] To enhance animation of lock button
- [x] To enhance photo preview (probably adding loading indicator)
- [x] To fix pen dock blockage to canvas
- [x] To add lift effect to pen thickness picker and zoom selector
