### ISSUE TITLE
[Dev] Fine-tune for iOS runtime

### ISSUE THREAD

**Issue by dscyrescotti** [dscyrescotti/Memola#55]
### Description
This is a call to refine the appearance of application for running on iOS (iPhone).

### Todos
- [x] To redesign canvas tools for iOS
- [x] To redesign canvas view
- [x] To redesign memo grid view
