### ISSUE TITLE
[Dev] Add memo preview render pipeline

### ISSUE THREAD

**Issue by dscyrescotti** [dscyrescotti/Memola#58]
### Description
Since the render pipeline is properly set up, it is good time to kick off the set up of preview render pipeline. The purpose is to show the preview image of graphic context in memo grid view so that the user can have the glimpse of what are inside. The pipeline should be completely separate from the draw render pipeline and it will requires to render all graphic contents.

### Todos
- [x] To store bounds of all graphic content in persistence
- [x] To set up preview render pipeline
- [x] To save and update preview image whenever closing memo
