### ISSUE TITLE
[Dev] Add macOS runtime target

### ISSUE THREAD

**Issue by dscyrescotti** [dscyrescotti/Memola#61]
### Description
This is a call to support macOS runtime so it includes the replacement of UIKit components with AppKit components.

### Todos
- [x] To add macOS target in project
- [x] To replace UIKit components
- [x] To update UI for dark mode
- [x] To set up command shortcuts
