### ISSUE TITLE
[Dev] Implement photo dock

### ISSUE THREAD

**Issue by dscyrescotti** [dscyrescotti/Memola#67]
### Description
Since photos are isolated in device storage, when the user adds the same photo more than twice, there are a lot of duplicated photos stored. So, it is a time to clean the mess up. The idea is that when the user select photo tool, it will show photo dock, which displays list or grid of photos added to dock. If the user wants to insert photo to canvas, they can simply drag and drop photo right away.

### Todos
- [x] To implement photo dock
- [x] To redesign database
- [x] To create file object
- [x] To link photo object to file object
- [x] To implement design for ipad and ios
